# Generated by Django 3.2.19 on 2023-06-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='className',
        ),
        migrations.AddField(
            model_name='detection',
            name='detectionError',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detection',
            name='lookingCenter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detection',
            name='lookingOther',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detection',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detection',
            name='sleeping',
            field=models.IntegerField(default=0),
        ),
    ]
