# Generated by Django 3.2.19 on 2023-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230602_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='noPerson',
            field=models.IntegerField(default=0),
        ),
    ]
