# Generated by Django 3.2.19 on 2023-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_detection_noperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noPerson', models.IntegerField(default=0)),
                ('sleeping', models.IntegerField(default=0)),
            ],
        ),
    ]
