# Generated by Django 3.2.19 on 2023-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
