# Generated by Django 3.2.19 on 2023-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230607_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='detectionError',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detection',
            name='lookingCenter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detection',
            name='lookingOther',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detection',
            name='noPerson',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detection',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='detection',
            name='sleeping',
            field=models.IntegerField(default=1),
        ),
    ]
